name: ${project.name}
version: ${project.version}-b${env.TRAVIS_BUILD_NUMBER}
description: ${project.description}
authors: [cereal, Sleaker, mung3r]
website: ${project.url}
api-version: 1.13

main: ${mainClass}
load: startup

commands:
  vault-info:
    description: Displays information about Vault.
    usage: |
           /<command> - Displays Vault information
    permission: vault.admin.info
  vault-convert:
    description: Converts the specified economy to another format.
    usage: |
           /<command> [economy1] [economy2]
    permission: vault.admin.convert
permissions:
  vault.admin:
    description: Allows using the administrative tools for Vault.
    default: op
    children:
      vault.admin.info: true
      vault.admin.convert: true
  vault.update:
    description: Notifies the player when Vault is in need of an update.
    default: op
